<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<properties>
		<java.version>17</java.version>
		<project.groupId>br.com.pawloandre.users</project.groupId>
		<project.artifactId>users</project.artifactId>
		<project.version>1.0.0-SNAPSHOT</project.version>
		<git-user>moreiracruz</git-user>
		<git-repository>pipeline</git-repository>
		<docker.image.prefix>${git-user}</docker.image.prefix>
		<project.build.finalName>${project.artifactId}-${project.version}</project.build.finalName>
	</properties>


	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.4.3</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>

	<groupId>br.com.moreiracruz</groupId>
	<artifactId>pipeline</artifactId>
	<version>0.0.1.1741764568-SNAPSHOT</version>
	<name>pipeline</name>
	<description>Pipeline</description>

	<url>https://www.moreiracruz.com.br</url>

	<licenses>
		<license>
			<name>MIT License</name>
			<url>https://opensource.org/licenses/MIT</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<developers>
		<developer>
			<name>Paulo André Moreira Cruz</name>
			<email>pawloandre@icloud.com</email>
			<url>https://www.moreiracruz.com.br</url>
			<organization>Moreira Cruz</organization>
			<organizationUrl>https://www.moreiracruz.com.br</organizationUrl>
			<roles>
				<role>Developer</role>
			</roles>
			<timezone>-3</timezone>
			<properties>
				<phone>+55 (83) 99637-7548</phone>
			</properties>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:git://github.com/${git-user}/${git-repository}.git</connection>
		<developerConnection>scm:git:https://github.com/${git-user}/${git-repository}.git</developerConnection>
		<tag>0.0.2</tag>
		<url>https://github.com/${git-user}/${git-repository}</url>
	</scm>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>3.0.1</version>
				<configuration>
					<autoVersionSubmodules>true</autoVersionSubmodules>
					<useReleaseProfile>false</useReleaseProfile>
					<releaseProfiles>release</releaseProfiles>
					<goals>deploy</goals>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<distributionManagement>
		<repository>
			<id>github</id>
			<name>GitHub OWNER Apache Maven Packages</name>
			<url>https://maven.pkg.github.com/moreiracruz/github</url>
		</repository>
	</distributionManagement>

	<profiles>
		<profile>
			<id>release</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-scm-plugin</artifactId>
						<configuration>
							<connectionType>developerConnection</connectionType>
							<developerConnection>scm:git:https://github.com/${git-user}/${git-repository}.git</developerConnection>
							<tagBase>scm:git:https://github.com/${git-user}/${git-repository}.git/tags</tagBase>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>