name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Configure Git user
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Setup SSH deploy key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Release Prepare
        run: mvn release:prepare -Dmaven.clean.failOnError=false
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TOKEN }}
      - name: Release Perform
        run: mvn release:perform -Dmaven.clean.failOnError=false
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TOKEN }}
      - name: Build and push Docker image (latest)
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout > final_name.txt
          FINAL_NAME=$(cat final_name.txt)
          docker build --build-arg FINAL_NAME=$FINAL_NAME -t ghcr.io/moreiracruz/pipeline:latest .
          docker push ghcr.io/moreiracruz/pipeline:latest
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TOKEN }}
      - name: Increment version and merge to main
        run: |
          git checkout main
          mvn versions:set -DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//' | awk -F. '{print $1"."$(($2+1))".0-SNAPSHOT"}')
          git commit -am "Increment version to $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_TOKEN }}
      - name: List .m2 directory
        run: ls -la ~/.m2
      - name: Clean Maven repository
        run: rm -rf ~/.m2/repository